### ISSUE TITLE
Spring 2.1.x => duplicate bean error

### ISSUE THREAD

**Issue by cer** [eventuate-tram/eventuate-tram-core#29]
```
***************************

APPLICATION FAILED TO START

***************************

 

Description:

 

The bean 'eventuateSchema', defined in io.eventuate.tram.messaging.producer.jdbc.TramMessageProducerJdbcConfiguration, could not be registered. A bean with that name has already been defined in io.eventuate.tram.consumer.kafka.TramConsumerKafkaConfiguration and overriding is disabled.

 

Action:

 

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

**Comment by cer** [comment]
Fixed by commit: https://github.com/eventuate-tram/eventuate-tram-core/commit/ad0c363ee14e1772c5e12624f61143fe311a0956

**Comment by SylvainAssemat** [comment]
HI 

I'm facing the same issue with my environement , in order to start the customer **and** order microservice.
I'm using the 2.1.4 version of Spring Boot.

Could you please help me to find out what's wrong ?

Thanks


```
------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Windows 10 10.0 amd64
```

```
$ docker container ls --format '{{.Names}}\t{{.Status}}\t{{.Ports}}'
rondo-saga_cdcservice_1 Up 4 minutes    0.0.0.0:8099->8080/tcp
rondo-saga_kafka_1      Up 4 minutes    0.0.0.0:9092->9092/tcp
rondo-saga_zookeeper_1  Up 4 minutes    0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp
rondo-saga_mysql_1      Up 4 minutes    0.0.0.0:3306->3306/tcp
```

``` 
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'eventuateSchema', defined in io.eventuate.tram.messaging.producer.jdbc.TramMessageProducerJdbcConfiguration, could not be registered. A bean with that name has already been defined in io.eventuate.tram.consumer.kafka.TramConsumerKafkaConfiguration and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

**Comment by cer** [comment]
This is an old issue. What version of Eventuate Tram are you using?

**Comment by eventuateio** [comment]
Try upgrading to the versions here: https://github.com/microservices-patterns/ftgo-application/blob/master/gradle.properties

**Comment by kushan-athukorala** [comment]
> Try upgrading to the versions here: https://github.com/microservices-patterns/ftgo-application/blob/master/gradle.properties

Thank you. I will test and confirm - 
https://eventuate-users.slack.com/archives/C3L9MNMQC/p1575428751027800

**Comment by kushan-athukorala** [comment]
I still see below error with those dependencies.

`The bean 'eventuateCommonJdbcOperations', defined in io.eventuate.common.jdbckafkastore.EventuateLocalConfiguration, could not be registered. A bean with that name has already been defined in class path resource [io/eventuate/tram/messaging/producer/jdbc/TramMessageProducerJdbcConfiguration.class] and overriding is disabled.`

Now the conflicting jars are,

```
eventuate-local-java-jdbc-0.31.0.RC3 --> EventuateLocalConfiguration --> eventuateCommonJdbcOperations()
and
eventuate-tram-producer-jdbc-0.22.0.RC5 -->  TramMessageProducerJdbcConfiguration --> eventuateCommonJdbcOperations()
```

**Comment by eventuateio** [comment]
Strange since https://github.com/microservices-patterns/ftgo-application/tree/master/ftgo-accounting-service uses both. I'll investigate.

**Comment by cer** [comment]
> Strange since https://github.com/microservices-patterns/ftgo-application/tree/master/ftgo-accounting-service uses both. I'll investigate.

Looks like ftgo-accounting-service is actually uses Spring Boot 2.0.x

**Comment by cer** [comment]
This should be properly fixed now.
See https://github.com/microservices-patterns/ftgo-application/blob/master/gradle.properties for a working set of library versions.

@kushan-athukorala
