### ISSUE TITLE
Would this support Oracle?

### ISSUE THREAD

**Issue by Princelo** [eventuate-tram/eventuate-tram-core#81]
Alternatively, Is It possible that the business services run with Oracle and sync the data about Eventuate Tram to MySQL for cdc service polling?

**Comment by cer** [comment]
Eventuate Tram should support Oracle using CDC polling (similar to how it supports MS SQL server):

1. Rebuild Eventuate CDC with the Oracle Drivers and possible the Oracle version of `EventuateSqlDialect`
2. Create the Oracle version of the Eventuate Schema
3. Configure the Eventuate CDC to run in polling mode

**Comment by Princelo** [comment]
thanks!
