### ISSUE TITLE
Missing publisher/subscriber mechanism for events/messages

### ISSUE THREAD

**Issue by mix42** [eventuate-tram/eventuate-tram-core#83]
It is not possible to publish an event which will be handled more than one service. In other words if one service(Service **A**) publishes the event/message, and many other services are subscribed to this event (**B and C**), only one service will receive it.

Tested with MySql polling, kafka.

**Comment by cer** [comment]
Each consumer - B and C - should have its own subscriberId (which corresponds to Kafka consumer group Id)

**Comment by mix42** [comment]
You are right. I was using the same subscriberId.

P.S.
Thank you for the great book.

**Comment by cer** [comment]
No worries.

Glad you like my book. I hope you find Eventuate tram useful too!

**Comment by mix42** [comment]
I like the framework very much and will promote it to be used in our projects!

**Comment by cer** [comment]
Excellent. Please don't hesitate to ask if you need assistance.
